version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build: .
    container_name: micrologs-app
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/MicroLogs
      RABBITMQ_URI: amqp://rabbitmq:5672
      QUEUE_NAME: MicroLogs
      API_PORT: 3000
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  mongodb_data:
